debug: true

irc:
  server:     irc.freenode.net
  port:       6667
  username:   bobobot
  nickname:   bobobot
  hostname:   example.com
  servername: exemple.com
  realname:   "BoBo Bot"

trusted_users:
  - f1gm3nt
  - testuser